spring:
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: juegos02
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          '[time_zone]': America/Argentina/Buenos_Aires
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: app
      uri: mongodb://localhost:27017/app?socketTimeoutMS=30000&connectTimeoutMS=10000&serverSelectionTimeoutMS=5000
    redis:
      host: localhost
      port: 6379

logging:
  level:
    '[org.springframework.jdbc.core.JdbcTemplate]': WARN
    '[org.hibernate.SQL]': WARN
    '[org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration]': WARN
    '[org.mongodb.driver.cluster]': WARN
    '[org.mongodb.driver.connection]': WARN
    '[org.hibernate.type]': WARN
    '[org.hibernate.stat]': WARN

# Configuraci√≥n para desarrollo local sin Docker
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: postgres
    password: juegos02
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: app
    redis:
      host: redis
      port: 6379